// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	docker "github.com/hostfactor/minecrafter/docker"
	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx, spec
func (_m *Interface) Build(ctx string, spec docker.BuildSpec) error {
	ret := _m.Called(ctx, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, docker.BuildSpec) error); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Push provides a mock function with given fields: tag
func (_m *Interface) Push(tag string) error {
	ret := _m.Called(tag)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
