// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SkipFunc is an autogenerated mock type for the SkipFunc type
type SkipFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: version, tag
func (_m *SkipFunc) Execute(version string, tag string) bool {
	ret := _m.Called(version, tag)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(version, tag)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
